### ISSUE TITLE
磁盘占用过多疑问

### ISSUE THREAD

**Issue by fiklekiki** [xyctruth/profiler#50]
我大概收集40多个服务，配置每分钟收集，一天大概增长10GB+。
我看每个profile文件才几kb。磁盘会占用这么多是正常的吗？

**Comment by xyctruth** [comment]
最主要是 go trace 的文件会很大，一个 trace 文件在 几百KB 至几M,  如果你不用分析 go trace 可以关闭收集 go trace。

```yaml
profileConfigs:
  trace:
    path: /debug/pprof/trace?seconds=10
    enable: false  #关闭
```
