### ISSUE TITLE
全部都设置了过期时间，但是磁盘还是在一直增长

### ISSUE THREAD

**Issue by fiklekiki** [xyctruth/profiler#84]

**Comment by z617015032** [comment]
我也遇到了这个问题，看着像设置的过期时间没生效，你现在解决了这个问题没

**Comment by xyctruth** [comment]
badger issues 中有很多类似的问题，我尝试着修改了一些参数, 比较忙还没来得及测试。可以尝试下版本 `v0.3.2`。

**Comment by z617015032** [comment]
1、我这边更新到最新版本 v0.3.2，测试但是数据过期时间参数还是没有生效
2、数据目录那些文件可以通过脚本的方式手动删除，而不影响最新数据的查询和使用，这个有什么办法吗？
3、对比这个工具和其他工具，感觉有一个不好的地方是，拉取同样的指标数据，磁盘占有率是其他工具的4倍，这个可以优化吗？

**Comment by xyctruth** [comment]
#98
