### ISSUE TITLE
使用 expiration 参数设置了过期时间不生效

### ISSUE THREAD

**Issue by z617015032** [xyctruth/profiler#98]
我这边更新到最新版本 v0.3.2，测试但是数据过期时间参数还是没有生效，而且服务也不拉取数据了
针对这个设置了过期时间不生效的问题，有没有临时方案来规避这个问题啊？

优化建议：
1、对比这个工具和其他工具，感觉有一个不好的地方是，拉取同样的指标数据，磁盘占有率是其他工具的4倍
2、页面标签选择我看是 `or` 的关系，可以修改成 `and` 的关系吗？

**Comment by xyctruth** [comment]
最近太忙了, 之后会去解决过期时间的问题。

优化建议1: 给否给出比较的方式
优化建议2: 其实 OR 和 AND 都能支持，只是不知道怎么在 ui 上表示出来，你有什么好的想法吗？

**Comment by z617015032** [comment]
1、我是对比 pyroscope 的服务，设置相同的拉取频率，发现磁盘使用差别比较大
2、前端是用什么框架实现

**Comment by xyctruth** [comment]
在 `v0.3.3`  有修改一些 badger 的配置，你可以尝试一下。我测试新写入的数据过期后会释放对应的磁盘空间。但是老的数据貌似还是不能立即释放。

**Comment by z617015032** [comment]
我使用这个镜像id 106f19e343b1 的镜像，发现是可以根据设置的过期时间删除数据的
